accounts/urls.py
from django.urls import path

from accounts import views as d

app_name = 'auth'
urlpatterns = [
    path('login/', d.login_view, name='login'),
    path('logout/', d.logout_view, name='logout'),
    path('register/', d.register, name='register'),
]

lists/urls.py
from django.urls import path

from lists import views

app_name = 'lists'
urlpatterns = [
    path('', views.index, name='index'),
    path('todolist/<int:todolist_id>/', views.todolist, name='todolist'),
    path('todolist/new/', views.new_todolist, name='new_todolist'),
    path('todolist/add/', views.add_todolist, name='add_todolist'),
    path('todo/add/<int:todolist_id>/', views.add_todo, name='add_todo'),
    path('todolists/', views.overview, name='overview'),
]

todolistproject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage,name="home"),
    path('auth/',include('accounts.urls'),name='accounts'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    path('thanks/',views.thanks,name='thanks'),
    path('lists/',include('lists.urls'),name='todolists'),


    ]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>TODO APP FOR HUAWEI</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  {% block css %}{% endblock %}
  {% block js %}{% endblock %}

<!-- <link rel="stylesheet" href="{% static 'todolistproject/css/master.css' %}"> -->

  </head>
  <body>
    <nav class="navbar mynav",role="navigation" id="navbar">
      <div class="container">
        <ul class="nav navbar-nav navbar-right">

          {% if user.is_authenticated %}
            <li class="navbar-item"><a class="navbar-link" href="{% url 'lists:index' %}">Add ToDO LIST</a></li>
              <li class="navbar-item">  <a  href="{% url 'lists:overview' %}">Your ToDO LIST</a></li>
              <li class="navbar-item">  <a  href="{% url 'auth:logout' %}">logout</a></li>

        </ul>




          {% else %}
            <li><a href="{% url 'auth:login' %}" class="btn btn-simple">Login</a></li>
            <li><a href="{% url 'auth:register' %}" class="btn btn-simple">SignUp</a></li>

          {% endif %}
        </ul>
      </div>

    </nav>
    <div class="container mycontent">
        {% block content %}
        {% endblock %}
    </div>





  </body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block content %}




<p>Welcome Our TODO APP</p>







{% endblock %}

templates/thanks.html
{% extends 'base.html' %}


{% block content %}




<h1>THANKS FOR VİSİTİNG OUR TODO APPS</h1>






{% endblock %}